name: Deploy Kofference.js App

on:
  push:
    branches:
      - gallery_c

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install

      - name: Build Vue.js App
        run: npm run build

      - name: Deploy to Server
        uses: appleboy/scp-action@gallery_c
        with:
          host: 172.16.18.148
          username: tamisemi
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "dist/"
          target: "/var/www/html/dist/"
