name: Build Vue.js App

on:
  push:
    branches:
      - gallery_c

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        run: |
          cd /var/www/html/koference-ui
          npm install

      - name: Build Vue.js App
<<<<<<< HEAD
        run: npm run build

      - name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
          host: 172.16.18.148
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SK }}
          port: ${{ secrets.SERVER_PORT }}
          source: "dist/"
          target: "/var/www/html/dist/"
=======
        run: |
          cd /var/www/html/koference-ui
          npm run build
>>>>>>> parent of 1118b1a (testing auto deploy)
